# Coconut IA server configuration file.

[Server]

  # Identifier is the human readable identifier for the node (eg: FQDN).
  Identifier = "Test IA Server"

  # Addresses are the IP address/port combinations that the server will bind
  # to for incoming connections.
  Addresses = [ "127.0.0.1:4000" ]

  # IsProvider specifies whether the server is a provider.
	# Currently it means it should be able to verify credentials it receives.
	IsProvider = true

	# IsIssuer specifies whether the server is a credential issuer.
	# Currently it means it should be able to sign attributes it receives.
	IsIssuer = true


[Issuer]

  # MaximumAttributes specifies the maximum number of attributes the server will sign.
  MaximumAttributes = 5

  # VerificationKeyFile specifies the file containing the Coconut Verification Key.
  VerificationKeyFile = "/home/jedrzej/go/src/github.com/jstuczyn/CoconutGo/ttp/keys3871/verification0-n=3-t=2.pem"

  # SecretKeyFile specifies the file containing the Coconut Secret Key.
  SecretKeyFile = "/home/jedrzej/go/src/github.com/jstuczyn/CoconutGo/ttp/keys3871/secret0-n=3-t=2.pem"


[Provider]

	# IAAddresses are the IP address:port combinations of all Authority Servers.
	# Required if the server is a provider.
  IAAddresses = [ "127.0.0.1:4000", "127.0.0.1:4001", "127.0.0.1:4002" ]

  # IAIDs are IDs of the servers used during generation of threshold keys.
  IAIDs = [ 1, 2, 3 ]
  
  # Threshold defines minimum number of verification keys provider needs to obtain. Default = len(IAAddresses).
  # TODO: should it be server or debug property?
  Threshold = 2


[Logging]

  # Disable disables logging entirely.
  Disable = false

  # File specifies the log file, if omitted stdout will be used.
  # File = "/var/log/coconutIA.log"

  # Level specifies the log level out of `CRITICAL`, `ERROR`, `WARNING`,
  # `NOTICE`, `INFO` and `DEBUG`.
  #
  # Warning: The `DEBUG` log level is unsafe for production use.
  Level = "DEBUG"


[Debug]

  # RegenerateKeys = true